print("안녕 파이썬!")
print("앞으로 잘 부탁해!")
print("Life is too short")
print("You need Python")
변수 = "자바" 
print("안녕" , 변수)
print("앞으로 잘 부탁해!")
print("안녕" , 변수)
print("앞으로 잘 부탁해!")
print("안녕" , 변수)
print("앞으로 잘 부탁해!")
print("안녕" , 변수)
print("앞으로 잘 부탁해!")
print("안녕" , 변수)
print("앞으로 잘 부탁해!")
print("안녕" , 변수)
print("앞으로 잘 부탁해!")
print("안녕" , 변수)
print("앞으로 잘 부탁해!")
print("안녕" , 변수)
print("앞으로 잘 부탁해!")
print("안녕" , 변수)
print("앞으로 잘 부탁해!")
print("안녕" , 변수)
print("앞으로 잘 부탁해!")
print("안녕" , 변수)
print("앞으로 잘 부탁해!")
print("안녕" , 변수)
print("앞으로 잘 부탁해!")
print("안녕" , 변수)
print("앞으로 잘 부탁해!")
print("안녕" , 변수)
print("앞으로 잘 부탁해!")
print("안녕" , 변수)
print("앞으로 잘 부탁해!")
print("안녕" , 변수)
print("앞으로 잘 부탁해!")
print("안녕" , 변수)
print("앞으로 잘 부탁해!")
print("안녕" , 변수)
print("앞으로 잘 부탁해!")
print("안녕" , 변수)
print("앞으로 잘 부탁해!")
print("안녕" , 변수)
print("앞으로 잘 부탁해!")
print("안녕" , 변수)
print("앞으로 잘 부탁해!")
print("안녕" , 변수)
print("앞으로 잘 부탁해!")
print("안녕" , 변수)
print("앞으로 잘 부탁해!")
print("안녕" , 변수)
print("앞으로 잘 부탁해!")
print("안녕" , 변수)
print("앞으로 잘 부탁해!")
print("안녕" , 변수)
print("앞으로 잘 부탁해!")
print("안녕" , 변수)
print("앞으로 잘 부탁해!")
print("안녕" , 변수)
print("앞으로 잘 부탁해!")
print("안녕" , 변수)
print("앞으로 잘 부탁해!")
print("안녕" , 변수)
print("앞으로 잘 부탁해!")
print("안녕" , 변수)
print("앞으로 잘 부탁해!")
print("안녕" , 변수)
print("앞으로 잘 부탁해!")
print("안녕" , 변수)
print("앞으로 잘 부탁해!")
print("안녕" , 변수)
print("앞으로 잘 부탁해!")
print("안녕" , 변수)
print("앞으로 잘 부탁해!")
print("안녕" , 변수)
print("앞으로 잘 부탁해!")
print("안녕" , 변수)
print("앞으로 잘 부탁해!")
print("안녕" , 변수)
print("앞으로 잘 부탁해!")
print("안녕" , 변수)
print("앞으로 잘 부탁해!")
print("안녕" , 변수)
print("앞으로 잘 부탁해!")
# 자주 쓸 것 같은, 자주 수정될 것 같은 것은 변수로 저장을 해놓는다.
# 변수(수학) : 변하는 수 (x,y,z)
# 변수(프로그래밍) : 저장공간 (값을 저장할 수 있는 공간)
# = (수학) : 왼쪽과 오른쪽은 같다
# = (프로그래밍) : 왼쪽에 있는 저장공간(변수)에 오른쪽에 있는 값을 담아라
a = 3
print("앞으로 잘 부탁해!",a,"또 연결")
# 변수 == 저장공간








